### ISSUE TITLE
Usage inside node app?

### ISSUE THREAD

**Issue by maotora** [telemark/robot-convert-docx-to-pdf#12]
Hi,

Is this project up for production?

Can I use it inside my node.js project?

Something like `require(...)`ing it in my code.

Thanks!

**Comment by zrrrzzt** [comment]
This project is in production but it is tailored to our specific needs. It is not created to be required.

If your goal is to convert docx to pdf you could build something yourself using a module like [better-unoconv](https://www.npmjs.com/package/better-unoconv).
Unoconv and LibreOffice/OpenOffice needs to be installed on your machine or you can use our pre-build [docker-image](https://hub.docker.com/r/telemark/docker-node-unoconv)

**Comment by maotora** [comment]
Oh thats good to know!

Thank you!
